#ifndef DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_INFO_H_INCLUDED
#define DISTRHO_PLUGIN_BRAND "Gabriel Garcia Alonso"
#define DISTRHO_PLUGIN_NAME "Granular Freeze"
#define DISTRHO_PLUGIN_URI "https://github.com/notgabriels-sys/VST"
#define DISTRHO_PLUGIN_CLAP_ID "com.gabrielgarciaalonso.granularfreeze"
#define DISTRHO_PLUGIN_BRAND_ID GFZP
#define DISTRHO_PLUGIN_UNIQUE_ID GF01
#define DISTRHO_PLUGIN_HAS_UI 1
#define DISTRHO_PLUGIN_IS_RT_SAFE 1
#define DISTRHO_PLUGIN_NUM_INPUTS 2
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT 0
#define DISTRHO_PLUGIN_WANT_MIDI_OUTPUT 0
#define DISTRHO_PLUGIN_WANT_DIRECT_ACCESS 1
#define DISTRHO_UI_USER_RESIZABLE 0
#define DISTRHO_UI_USE_NANOVG 1
#define DISTRHO_UI_DEFAULT_WIDTH 720
#define DISTRHO_UI_DEFAULT_HEIGHT 360
#endif
